// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TTI.TTF.Taxonomy {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEgh0YXhvbm9teRoOdGF4b25vbXkucHJvdG8aCmNv",
            "cmUucHJvdG8aDmFydGlmYWN0LnByb3RvGhtnb29nbGUvcHJvdG9idWYvRW1w",
            "dHkucHJvdG8yjg0KB1NlcnZpY2USTgoPR2V0RnVsbFRheG9ub215Eh8udGF4",
            "b25vbXkubW9kZWwuVGF4b25vbXlWZXJzaW9uGhgudGF4b25vbXkubW9kZWwu",
            "VGF4b25vbXkiABJXCg9HZXRCYXNlQXJ0aWZhY3QSJy50YXhvbm9teS5tb2Rl",
            "bC5hcnRpZmFjdC5BcnRpZmFjdFN5bWJvbBoZLnRheG9ub215Lm1vZGVsLmNv",
            "cmUuQmFzZSIAEl8KE0dldEJlaGF2aW9yQXJ0aWZhY3QSJy50YXhvbm9teS5t",
            "b2RlbC5hcnRpZmFjdC5BcnRpZmFjdFN5bWJvbBodLnRheG9ub215Lm1vZGVs",
            "LmNvcmUuQmVoYXZpb3IiABJpChhHZXRCZWhhdmlvckdyb3VwQXJ0aWZhY3QS",
            "Jy50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5BcnRpZmFjdFN5bWJvbBoiLnRh",
            "eG9ub215Lm1vZGVsLmNvcmUuQmVoYXZpb3JHcm91cCIAEmUKFkdldFByb3Bl",
            "cnR5U2V0QXJ0aWZhY3QSJy50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5BcnRp",
            "ZmFjdFN5bWJvbBogLnRheG9ub215Lm1vZGVsLmNvcmUuUHJvcGVydHlTZXQi",
            "ABJtChpHZXRUZW1wbGF0ZUZvcm11bGFBcnRpZmFjdBInLnRheG9ub215Lm1v",
            "ZGVsLmFydGlmYWN0LkFydGlmYWN0U3ltYm9sGiQudGF4b25vbXkubW9kZWwu",
            "Y29yZS5UZW1wbGF0ZUZvcm11bGEiABJzCh1HZXRUZW1wbGF0ZURlZmluaXRp",
            "b25BcnRpZmFjdBInLnRheG9ub215Lm1vZGVsLmFydGlmYWN0LkFydGlmYWN0",
            "U3ltYm9sGicudGF4b25vbXkubW9kZWwuY29yZS5UZW1wbGF0ZURlZmluaXRp",
            "b24iABJiChBHZXRUb2tlblRlbXBsYXRlEigudGF4b25vbXkubW9kZWwuYXJ0",
            "aWZhY3QuVG9rZW5UZW1wbGF0ZUlkGiIudGF4b25vbXkubW9kZWwuY29yZS5U",
            "b2tlblRlbXBsYXRlIgASbAoVR2V0VG9rZW5TcGVjaWZpY2F0aW9uEigudGF4",
            "b25vbXkubW9kZWwuYXJ0aWZhY3QuVG9rZW5UZW1wbGF0ZUlkGicudGF4b25v",
            "bXkubW9kZWwuY29yZS5Ub2tlblNwZWNpZmljYXRpb24iABJjChJHZXRBcnRp",
            "ZmFjdHNPZlR5cGUSJS50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5RdWVyeU9w",
            "dGlvbnMaJC50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5RdWVyeVJlc3VsdCIA",
            "Em0KDkNyZWF0ZUFydGlmYWN0EisudGF4b25vbXkubW9kZWwuYXJ0aWZhY3Qu",
            "TmV3QXJ0aWZhY3RSZXF1ZXN0GiwudGF4b25vbXkubW9kZWwuYXJ0aWZhY3Qu",
            "TmV3QXJ0aWZhY3RSZXNwb25zZSIAEnMKDlVwZGF0ZUFydGlmYWN0Ei4udGF4",
            "b25vbXkubW9kZWwuYXJ0aWZhY3QuVXBkYXRlQXJ0aWZhY3RSZXF1ZXN0Gi8u",
            "dGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuVXBkYXRlQXJ0aWZhY3RSZXNwb25z",
            "ZSIAEnMKDkRlbGV0ZUFydGlmYWN0Ei4udGF4b25vbXkubW9kZWwuYXJ0aWZh",
            "Y3QuRGVsZXRlQXJ0aWZhY3RSZXF1ZXN0Gi8udGF4b25vbXkubW9kZWwuYXJ0",
            "aWZhY3QuRGVsZXRlQXJ0aWZhY3RSZXNwb25zZSIAEnUKEkNvbW1pdExvY2Fs",
            "VXBkYXRlcxItLnRheG9ub215Lm1vZGVsLmFydGlmYWN0LkNvbW1pdFVwZGF0",
            "ZXNSZXF1ZXN0Gi4udGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuQ29tbWl0VXBk",
            "YXRlc1Jlc3BvbnNlIgASZgoLUHVsbFJlcXVlc3QSKS50YXhvbm9teS5tb2Rl",
            "bC5hcnRpZmFjdC5Jc3N1ZVB1bGxSZXF1ZXN0GioudGF4b25vbXkubW9kZWwu",
            "YXJ0aWZhY3QuSXNzdWVQdWxsUmVzcG9uc2UiABJUCglHZXRDb25maWcSFi5n",
            "b29nbGUucHJvdG9idWYuRW1wdHkaLS50YXhvbm9teS5tb2RlbC5hcnRpZmFj",
            "dC5TZXJ2aWNlQ29uZmlndXJhdGlvbiIAQisKFG9yZy50dGkudHRmLnRheG9u",
            "b215UAGqAhBUVEkuVFRGLlRheG9ub215YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TTI.TTF.Taxonomy.Model.TaxonomyReflection.Descriptor, global::TTI.TTF.Taxonomy.Model.Core.CoreReflection.Descriptor, global::TTI.TTF.Taxonomy.Model.Artifact.ArtifactReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
