// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TTI.TTF.Taxonomy {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEgh0YXhvbm9teRoOdGF4b25vbXkucHJvdG8aCmNv",
            "cmUucHJvdG8aDmFydGlmYWN0LnByb3RvGhtnb29nbGUvcHJvdG9idWYvRW1w",
            "dHkucHJvdG8yxAoKB1NlcnZpY2USTgoPR2V0RnVsbFRheG9ub215Eh8udGF4",
            "b25vbXkubW9kZWwuVGF4b25vbXlWZXJzaW9uGhgudGF4b25vbXkubW9kZWwu",
            "VGF4b25vbXkiABJXCg9HZXRCYXNlQXJ0aWZhY3QSJy50YXhvbm9teS5tb2Rl",
            "bC5hcnRpZmFjdC5BcnRpZmFjdFN5bWJvbBoZLnRheG9ub215Lm1vZGVsLmNv",
            "cmUuQmFzZSIAEl8KE0dldEJlaGF2aW9yQXJ0aWZhY3QSJy50YXhvbm9teS5t",
            "b2RlbC5hcnRpZmFjdC5BcnRpZmFjdFN5bWJvbBodLnRheG9ub215Lm1vZGVs",
            "LmNvcmUuQmVoYXZpb3IiABJpChhHZXRCZWhhdmlvckdyb3VwQXJ0aWZhY3QS",
            "Jy50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5BcnRpZmFjdFN5bWJvbBoiLnRh",
            "eG9ub215Lm1vZGVsLmNvcmUuQmVoYXZpb3JHcm91cCIAEmUKFkdldFByb3Bl",
            "cnR5U2V0QXJ0aWZhY3QSJy50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5BcnRp",
            "ZmFjdFN5bWJvbBogLnRheG9ub215Lm1vZGVsLmNvcmUuUHJvcGVydHlTZXQi",
            "ABJqChhHZXRUb2tlblRlbXBsYXRlQXJ0aWZhY3QSKC50YXhvbm9teS5tb2Rl",
            "bC5hcnRpZmFjdC5UYXhvbm9teUZvcm11bGEaIi50YXhvbm9teS5tb2RlbC5j",
            "b3JlLlRva2VuVGVtcGxhdGUiABJjChJHZXRBcnRpZmFjdHNPZlR5cGUSJS50",
            "YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5RdWVyeU9wdGlvbnMaJC50YXhvbm9t",
            "eS5tb2RlbC5hcnRpZmFjdC5RdWVyeVJlc3VsdCIAEm0KDkNyZWF0ZUFydGlm",
            "YWN0EisudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuTmV3QXJ0aWZhY3RSZXF1",
            "ZXN0GiwudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuTmV3QXJ0aWZhY3RSZXNw",
            "b25zZSIAEnMKDlVwZGF0ZUFydGlmYWN0Ei4udGF4b25vbXkubW9kZWwuYXJ0",
            "aWZhY3QuVXBkYXRlQXJ0aWZhY3RSZXF1ZXN0Gi8udGF4b25vbXkubW9kZWwu",
            "YXJ0aWZhY3QuVXBkYXRlQXJ0aWZhY3RSZXNwb25zZSIAEnMKDkRlbGV0ZUFy",
            "dGlmYWN0Ei4udGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuRGVsZXRlQXJ0aWZh",
            "Y3RSZXF1ZXN0Gi8udGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuRGVsZXRlQXJ0",
            "aWZhY3RSZXNwb25zZSIAEnUKEkNvbW1pdExvY2FsVXBkYXRlcxItLnRheG9u",
            "b215Lm1vZGVsLmFydGlmYWN0LkNvbW1pdFVwZGF0ZXNSZXF1ZXN0Gi4udGF4",
            "b25vbXkubW9kZWwuYXJ0aWZhY3QuQ29tbWl0VXBkYXRlc1Jlc3BvbnNlIgAS",
            "ZgoLUHVsbFJlcXVlc3QSKS50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5Jc3N1",
            "ZVB1bGxSZXF1ZXN0GioudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuSXNzdWVQ",
            "dWxsUmVzcG9uc2UiABJUCglHZXRDb25maWcSFi5nb29nbGUucHJvdG9idWYu",
            "RW1wdHkaLS50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5TZXJ2aWNlQ29uZmln",
            "dXJhdGlvbiIAQisKFG9yZy50dGkudHRmLnRheG9ub215UAGqAhBUVEkuVFRG",
            "LlRheG9ub215YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TTI.TTF.Taxonomy.Model.TaxonomyReflection.Descriptor, global::TTI.TTF.Taxonomy.Model.Core.CoreReflection.Descriptor, global::TTI.TTF.Taxonomy.Model.Artifact.ArtifactReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
