// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: taxonomyservice.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TTI.TTF.Taxonomy {

  /// <summary>Holder for reflection information generated from taxonomyservice.proto</summary>
  public static partial class TaxonomyserviceReflection {

    #region Descriptor
    /// <summary>File descriptor for taxonomyservice.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TaxonomyserviceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChV0YXhvbm9teXNlcnZpY2UucHJvdG8SEHRheG9ub215LnNlcnZpY2UaDnRh",
            "eG9ub215LnByb3RvGgpjb3JlLnByb3RvGg5hcnRpZmFjdC5wcm90bzKyBwoP",
            "VGF4b25vbXlTZXJ2aWNlEk4KD0dldEZ1bGxUYXhvbm9teRIfLnRheG9ub215",
            "Lm1vZGVsLlRheG9ub215VmVyc2lvbhoYLnRheG9ub215Lm1vZGVsLlRheG9u",
            "b215IgASVwoPR2V0QmFzZUFydGlmYWN0EicudGF4b25vbXkubW9kZWwuYXJ0",
            "aWZhY3QuQXJ0aWZhY3RTeW1ib2waGS50YXhvbm9teS5tb2RlbC5jb3JlLkJh",
            "c2UiABJfChNHZXRCZWhhdmlvckFydGlmYWN0EicudGF4b25vbXkubW9kZWwu",
            "YXJ0aWZhY3QuQXJ0aWZhY3RTeW1ib2waHS50YXhvbm9teS5tb2RlbC5jb3Jl",
            "LkJlaGF2aW9yIgASaQoYR2V0QmVoYXZpb3JHcm91cEFydGlmYWN0EicudGF4",
            "b25vbXkubW9kZWwuYXJ0aWZhY3QuQXJ0aWZhY3RTeW1ib2waIi50YXhvbm9t",
            "eS5tb2RlbC5jb3JlLkJlaGF2aW9yR3JvdXAiABJlChZHZXRQcm9wZXJ0eVNl",
            "dEFydGlmYWN0EicudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuQXJ0aWZhY3RT",
            "eW1ib2waIC50YXhvbm9teS5tb2RlbC5jb3JlLlByb3BlcnR5U2V0IgASagoY",
            "R2V0VG9rZW5UZW1wbGF0ZUFydGlmYWN0EigudGF4b25vbXkubW9kZWwuYXJ0",
            "aWZhY3QuVGF4b25vbXlGb3JtdWxhGiIudGF4b25vbXkubW9kZWwuY29yZS5U",
            "b2tlblRlbXBsYXRlIgASbQoOQ3JlYXRlQXJ0aWZhY3QSKy50YXhvbm9teS5t",
            "b2RlbC5hcnRpZmFjdC5OZXdBcnRpZmFjdFJlcXVlc3QaLC50YXhvbm9teS5t",
            "b2RlbC5hcnRpZmFjdC5OZXdBcnRpZmFjdFJlc3BvbnNlIgAScwoOVXBkYXRl",
            "QXJ0aWZhY3QSLi50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5VcGRhdGVBcnRp",
            "ZmFjdFJlcXVlc3QaLy50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5VcGRhdGVB",
            "cnRpZmFjdFJlc3BvbnNlIgAScwoORGVsZXRlQXJ0aWZhY3QSLi50YXhvbm9t",
            "eS5tb2RlbC5hcnRpZmFjdC5EZWxldGVBcnRpZmFjdFJlcXVlc3QaLy50YXhv",
            "bm9teS5tb2RlbC5hcnRpZmFjdC5EZWxldGVBcnRpZmFjdFJlc3BvbnNlIgBC",
            "KwoUb3JnLnR0aS50dGYudGF4b25vbXlQAaoCEFRUSS5UVEYuVGF4b25vbXli",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TTI.TTF.Taxonomy.Model.TaxonomyReflection.Descriptor, global::TTI.TTF.Taxonomy.Model.Core.CoreReflection.Descriptor, global::TTI.TTF.Taxonomy.Model.Artifact.ArtifactReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
