// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TTI.TTF.Taxonomy {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEgh0YXhvbm9teRoOdGF4b25vbXkucHJvdG8aCmNv",
            "cmUucHJvdG8aDmFydGlmYWN0LnByb3RvGhtnb29nbGUvcHJvdG9idWYvRW1w",
            "dHkucHJvdG8y3g0KB1NlcnZpY2USTgoPR2V0RnVsbFRheG9ub215Eh8udGF4",
            "b25vbXkubW9kZWwuVGF4b25vbXlWZXJzaW9uGhgudGF4b25vbXkubW9kZWwu",
            "VGF4b25vbXkiABJOCg9HZXRMaXRlVGF4b25vbXkSHy50YXhvbm9teS5tb2Rl",
            "bC5UYXhvbm9teVZlcnNpb24aGC50YXhvbm9teS5tb2RlbC5UYXhvbm9teSIA",
            "ElcKD0dldEJhc2VBcnRpZmFjdBInLnRheG9ub215Lm1vZGVsLmFydGlmYWN0",
            "LkFydGlmYWN0U3ltYm9sGhkudGF4b25vbXkubW9kZWwuY29yZS5CYXNlIgAS",
            "XwoTR2V0QmVoYXZpb3JBcnRpZmFjdBInLnRheG9ub215Lm1vZGVsLmFydGlm",
            "YWN0LkFydGlmYWN0U3ltYm9sGh0udGF4b25vbXkubW9kZWwuY29yZS5CZWhh",
            "dmlvciIAEmkKGEdldEJlaGF2aW9yR3JvdXBBcnRpZmFjdBInLnRheG9ub215",
            "Lm1vZGVsLmFydGlmYWN0LkFydGlmYWN0U3ltYm9sGiIudGF4b25vbXkubW9k",
            "ZWwuY29yZS5CZWhhdmlvckdyb3VwIgASZQoWR2V0UHJvcGVydHlTZXRBcnRp",
            "ZmFjdBInLnRheG9ub215Lm1vZGVsLmFydGlmYWN0LkFydGlmYWN0U3ltYm9s",
            "GiAudGF4b25vbXkubW9kZWwuY29yZS5Qcm9wZXJ0eVNldCIAEm0KGkdldFRl",
            "bXBsYXRlRm9ybXVsYUFydGlmYWN0EicudGF4b25vbXkubW9kZWwuYXJ0aWZh",
            "Y3QuQXJ0aWZhY3RTeW1ib2waJC50YXhvbm9teS5tb2RlbC5jb3JlLlRlbXBs",
            "YXRlRm9ybXVsYSIAEnMKHUdldFRlbXBsYXRlRGVmaW5pdGlvbkFydGlmYWN0",
            "EicudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuQXJ0aWZhY3RTeW1ib2waJy50",
            "YXhvbm9teS5tb2RlbC5jb3JlLlRlbXBsYXRlRGVmaW5pdGlvbiIAEmIKEEdl",
            "dFRva2VuVGVtcGxhdGUSKC50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5Ub2tl",
            "blRlbXBsYXRlSWQaIi50YXhvbm9teS5tb2RlbC5jb3JlLlRva2VuVGVtcGxh",
            "dGUiABJsChVHZXRUb2tlblNwZWNpZmljYXRpb24SKC50YXhvbm9teS5tb2Rl",
            "bC5hcnRpZmFjdC5Ub2tlblRlbXBsYXRlSWQaJy50YXhvbm9teS5tb2RlbC5j",
            "b3JlLlRva2VuU3BlY2lmaWNhdGlvbiIAEmMKEkdldEFydGlmYWN0c09mVHlw",
            "ZRIlLnRheG9ub215Lm1vZGVsLmFydGlmYWN0LlF1ZXJ5T3B0aW9ucxokLnRh",
            "eG9ub215Lm1vZGVsLmFydGlmYWN0LlF1ZXJ5UmVzdWx0IgASbQoOQ3JlYXRl",
            "QXJ0aWZhY3QSKy50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5OZXdBcnRpZmFj",
            "dFJlcXVlc3QaLC50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5OZXdBcnRpZmFj",
            "dFJlc3BvbnNlIgAScwoOVXBkYXRlQXJ0aWZhY3QSLi50YXhvbm9teS5tb2Rl",
            "bC5hcnRpZmFjdC5VcGRhdGVBcnRpZmFjdFJlcXVlc3QaLy50YXhvbm9teS5t",
            "b2RlbC5hcnRpZmFjdC5VcGRhdGVBcnRpZmFjdFJlc3BvbnNlIgAScwoORGVs",
            "ZXRlQXJ0aWZhY3QSLi50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5EZWxldGVB",
            "cnRpZmFjdFJlcXVlc3QaLy50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5EZWxl",
            "dGVBcnRpZmFjdFJlc3BvbnNlIgASdQoSQ29tbWl0TG9jYWxVcGRhdGVzEi0u",
            "dGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuQ29tbWl0VXBkYXRlc1JlcXVlc3Qa",
            "Li50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5Db21taXRVcGRhdGVzUmVzcG9u",
            "c2UiABJmCgtQdWxsUmVxdWVzdBIpLnRheG9ub215Lm1vZGVsLmFydGlmYWN0",
            "Lklzc3VlUHVsbFJlcXVlc3QaKi50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5J",
            "c3N1ZVB1bGxSZXNwb25zZSIAElQKCUdldENvbmZpZxIWLmdvb2dsZS5wcm90",
            "b2J1Zi5FbXB0eRotLnRheG9ub215Lm1vZGVsLmFydGlmYWN0LlNlcnZpY2VD",
            "b25maWd1cmF0aW9uIgBCKwoUb3JnLnR0aS50dGYudGF4b25vbXlQAaoCEFRU",
            "SS5UVEYuVGF4b25vbXliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TTI.TTF.Taxonomy.Model.TaxonomyReflection.Descriptor, global::TTI.TTF.Taxonomy.Model.Core.CoreReflection.Descriptor, global::TTI.TTF.Taxonomy.Model.Artifact.ArtifactReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
