// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: taxonomyservice.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TTI.TTF.Taxonomy {

  /// <summary>Holder for reflection information generated from taxonomyservice.proto</summary>
  public static partial class TaxonomyserviceReflection {

    #region Descriptor
    /// <summary>File descriptor for taxonomyservice.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TaxonomyserviceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChV0YXhvbm9teXNlcnZpY2UucHJvdG8SEHRheG9ub215LnNlcnZpY2UaDnRh",
            "eG9ub215LnByb3RvGgpjb3JlLnByb3RvGg5hcnRpZmFjdC5wcm90bzLlBgoP",
            "VGF4b25vbXlTZXJ2aWNlEk4KD0dldEZ1bGxUYXhvbm9teRIfLnRheG9ub215",
            "Lm1vZGVsLlRheG9ub215VmVyc2lvbhoYLnRheG9ub215Lm1vZGVsLlRheG9u",
            "b215IgASRgoPR2V0QmFzZUFydGlmYWN0EhYudGF4b25vbXkubW9kZWwuU3lt",
            "Ym9sGhkudGF4b25vbXkubW9kZWwuY29yZS5CYXNlIgASTgoTR2V0QmVoYXZp",
            "b3JBcnRpZmFjdBIWLnRheG9ub215Lm1vZGVsLlN5bWJvbBodLnRheG9ub215",
            "Lm1vZGVsLmNvcmUuQmVoYXZpb3IiABJYChhHZXRCZWhhdmlvckdyb3VwQXJ0",
            "aWZhY3QSFi50YXhvbm9teS5tb2RlbC5TeW1ib2waIi50YXhvbm9teS5tb2Rl",
            "bC5jb3JlLkJlaGF2aW9yR3JvdXAiABJUChZHZXRQcm9wZXJ0eVNldEFydGlm",
            "YWN0EhYudGF4b25vbXkubW9kZWwuU3ltYm9sGiAudGF4b25vbXkubW9kZWwu",
            "Y29yZS5Qcm9wZXJ0eVNldCIAEmEKGEdldFRva2VuVGVtcGxhdGVBcnRpZmFj",
            "dBIfLnRheG9ub215Lm1vZGVsLlRheG9ub215Rm9ybXVsYRoiLnRheG9ub215",
            "Lm1vZGVsLmNvcmUuVG9rZW5UZW1wbGF0ZSIAEm0KDkNyZWF0ZUFydGlmYWN0",
            "EisudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuTmV3QXJ0aWZhY3RSZXF1ZXN0",
            "GiwudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuTmV3QXJ0aWZhY3RSZXNwb25z",
            "ZSIAEnMKDlVwZGF0ZUFydGlmYWN0Ei4udGF4b25vbXkubW9kZWwuYXJ0aWZh",
            "Y3QuVXBkYXRlQXJ0aWZhY3RSZXF1ZXN0Gi8udGF4b25vbXkubW9kZWwuYXJ0",
            "aWZhY3QuVXBkYXRlQXJ0aWZhY3RSZXNwb25zZSIAEnMKDkRlbGV0ZUFydGlm",
            "YWN0Ei4udGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuRGVsZXRlQXJ0aWZhY3RS",
            "ZXF1ZXN0Gi8udGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuRGVsZXRlQXJ0aWZh",
            "Y3RSZXNwb25zZSIAQisKFG9yZy50dGkudHRmLnRheG9ub215UAGqAhBUVEku",
            "VFRGLlRheG9ub215YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TTI.TTF.Taxonomy.Model.TaxonomyReflection.Descriptor, global::TTI.TTF.Taxonomy.Model.Core.CoreReflection.Descriptor, global::TTI.TTF.Taxonomy.Model.Artifact.ArtifactReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
